services:
  # A web service for the Django application
  - type: web
    name: blog-app
    env: python
    region: oregon # Use the region closest to your users
    plan: free # Use free tier    buildCommand: ./build.sh
    startCommand: cd DJANGO_PROJECT && python -m gunicorn wsgi:application
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.1
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOST
        value: blog-app.onrender.com

# A PostgreSQL database
databases:
  - name: blog-db
    plan: free
    databaseName: blogdb
    user: bloguser